# Generated by Django 3.2.3 on 2021-05-28 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PositionModel',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('vendor_code', models.CharField(max_length=13)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=50)),
                ('contract_expire', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerModel',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.departmentmodel')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.positionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='WriteOffReasonModel',
            fields=[
                ('reason_id', models.AutoField(primary_key=True, serialize=False)),
                ('write_off_reason', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WriteOffProductModel',
            fields=[
                ('write_off_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.productmodel')),
                ('reason_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.writeoffreasonmodel')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.workermodel')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyModel',
            fields=[
                ('supply_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('supply_date', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.productmodel')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.providermodel')),
            ],
        ),
        migrations.CreateModel(
            name='SaleModel',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_cost', models.FloatField()),
                ('sale_date', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.clientmodel')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.productmodel')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.workermodel')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCardModel',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_value', models.FloatField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_view.clientmodel')),
            ],
        ),
    ]
