# Generated by Django 3.2.3 on 2021-05-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_view', '0002_auto_20210529_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='vendor_code',
            field=models.IntegerField(),
        ),
    ]
