# Generated by Django 3.2.3 on 2021-05-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_view', '0004_alter_productmodel_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='vendor_code',
            field=models.IntegerField(),
        ),
    ]
